# Generated by Django 4.2.7 on 2023-11-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
