# Generated by Django 4.2.7 on 2023-12-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosevent', '0002_event_price_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owner',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='artist_name',
        ),
    ]
