# Generated by Django 4.2.7 on 2024-01-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cosevent', '0006_video_event_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cosevent.video'),
        ),
    ]
